layout: {zmk_keyboard: cradio}
layers:
  Base:
  - [Q, W, E, R, T, Y, U, I, O, P]
  - - {t: A, h: LSHIFT}
    - {t: S, h: LALT}
    - {t: D, h: LCTRL}
    - {t: F, h: LGUI}
    - G
    - H
    - {t: J, h: RGUI}
    - {t: K, h: RCTRL}
    - {t: L, h: RALT}
    - {t: ;, h: RSHIFT}
  - [Z, X, C, V, B, N, M, ',', ., /]
  - - {t: BKSP, h: Symbols}
    - DEL
    - TAB
    - {t: SPACE, h: Numbers}
  Symbols:
  - - '!'
    - '@'
    - '#'
    - $
    - '%'
    - ^
    - '&'
    - '*'
    - {t: '-', h: _}
    - '='
  - - {t: ESC, h: LSHIFT}
    - {t: '`', h: LALT}
    - {t: '''', h: LCTRL}
    - {t: '"', h: LGUI}
    - ''
    - ''
    - {t: (, h: RGUI}
    - {t: ), h: RCTRL}
    - {t: \, h: RALT}
    - {t: ENTER, h: RSHIFT}
  - ['~', '', LEFT, RIGHT, '', '', UP, DOWN, '[', ']']
  - - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  Numbers:
  - ['', fn20-24, fn10-19, fn1-9, '', '', '7', '8', '9', '']
  - - LSHIFT
    - LALT
    - LCTRL
    - LGUI
    - ''
    - ''
    - {t: '4', h: RGUI}
    - {t: '5', h: RCTRL}
    - {t: '6', h: RALT}
    - {t: ENTER, h: RSHIFT}
  - ['', '', '', '', '', '', '1', '2', '3', '0']
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
  Control:
  - ['', '', '', '', '', '', '', '', '', '&studio_unlock']
  - - {t: BT, h: '3'}
    - {t: BT, h: '2'}
    - {t: BT, h: '1'}
    - {t: BT, h: '0'}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  - ['&studio_unlock', '', '', '', '&bootloader', '&bootloader', '', '', '', BT CLR]
  - - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
  fn1-9:
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F7
    - F8
    - F9
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F4
    - F5
    - F6
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F1
    - F2
    - F3
    - F10
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
  fn10-19:
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F17
    - F18
    - F19
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F14
    - F15
    - F16
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F11
    - F12
    - F13
    - F10
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
  fn20-24:
  - - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F24
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - F21
    - F22
    - F23
    - F20
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
combos:
- p: [13, 16]
  k: LWIN
  l: [Base]
